version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - mysqldata:/var/lib/mysql
    # networks:
    #   - default

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./:/usr/src/app
  #   ports:
  #     - "3000:3000"
  #     - "5555:5555"
  #   networks:
  #     - default
  #   depends_on:
  #     - mysql

# networks:
#   default:

volumes:
  mysqldata: